---
- name: Configure Monitor Size
  copy: src=monitor.conf dest=/etc/X11/xorg.conf.d/90-monitor.conf
- name: Configure Qt5 HiDPI Scaling
  copy: src=qt-hidpi.sh dest=/etc/profile.d/qt-hidpi.sh mode=0755
