---
- pacman: name=docker state=present
- service: name=docker enabled=yes
- command: docker-compose --version
  become: no
  register: docker_compose_version
  ignore_errors: True
- name: Download Docker Compose
  shell: curl -L https://github.com/docker/compose/releases/download/{{docker_compose}}/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  when: docker_compose_version.stdout.find('{{docker_compose}}') == -1
- name: Adjust Docker Compose Permissions
  file:
    path: /usr/local/bin/docker-compose
    group: root
    owner: root
    mode: 0755
