---
- include: hostname.yml
- include: packages.yml
- include: clean-pacman-cache.yml
- include: home.yml
- include: firewall.yml
- include: time.yml
- include: docker.yml
- include: dropbox.yml
- include: mouse.yml
- include: vagrant.yml
- include: power.yml
- include: u2f.yml
