---
- include: hostname.yml
- include: dns.yml
- include: network.yml
- include: pacman.yml
- include: packages.yml
- include: mimeo.yml
- include: scala.yml
- include: clean-pacman-cache.yml
- include: docker.yml
- include: home.yml
- include: asdf.yml
- include: firewall.yml
- include: time.yml
- include: dropbox.yml
- include: sound.yml
- include: fonts.yml
- include: mouse.yml
- include: vagrant.yml
- include: power.yml
- include: display.yml
- include: u2f.yml
- include: xorg.yml
- include: swap.yml
