---
- include: hostname.yml
- include: dns.yml
- include: pacman.yml
- include: packages.yml
- include: clean-pacman-cache.yml
- include: docker.yml
- include: home.yml
- include: firewall.yml
- include: fstab.yml
- include: time.yml
- include: dropbox.yml
- include: sound.yml
- include: fonts.yml
- include: mouse.yml
- include: vagrant.yml
- include: power.yml
- include: display.yml
- include: u2f.yml
- include: xorg.yml
- include: scanner.yml
