---
- include: package-bundle.yml pkg=base-devel
- include: package-bundle.yml pkg=lxde
# Used for pandoc PDF conversions.
- include: package-bundle.yml pkg=texlive-most
- include: package-bundle.yml pkg=dnsutils
- name: Install Pacman Packages
  pacman: name={{ item }} state=present
  with_items:
    - abs
    - acpi
    - acpid
    - alsa-oss
    - alsa-utils
    - avahi
    - bc
    - bluez
    - bluez-utils
    - cairo                 # Fonts (Vector Graphics Library)
    - chromium              # Browser.
    - coreutils
    - crystal               # Crystal Programming Language
    - ctags
    - cups                  # Printer management.
    - curl
    - erlang                # Full Erlang (out of order on purpose)
    - elixir                # Elixir Programming Language
    - encfs                 # File Encryption
    - eog                   # Image Viewer
    - evince
    - exfat-utils           # exFAT filesystem support
    - expac
    - darktable             # Image Workflow and Editing
    - doxygen               # C Development: documentation generation.
    - fontconfig            # Fonts
    - freetype2             # Fonts
    - fzf                   # Command line fuzzy finder.
    - gdb                   # C Development: debugger.
    - ghc                   # Haskell Compiler
    - ghostscript
    - glibc                 # C Development: GNU C Library.
    - gnupg
    - gnuplot               # GNU command line plotting utility
    - go                    # Go Programming Language
    - gsfonts
    - gsl                   # C Development: GNU Scientific Library.
    - gtk3
    - gtk3-print-backends   # Print from Gtk3 applications.
    - gutenprint
    - guvcview              # Webcam configuration utility.
    - gvim
    - haskell-quickcheck    # Haskell testing library.
    - hub                   # GitHub CLI for Git
    - i3lock                # Screen Locker
    - icedtea-web
    - imagemagick           # Image stuff and convert.
    - jq                    # Command-line JSON parser.
    - kdenlive              # Video Editing.
    - keepassx2
    - keybase
    - libcups
    - libmtp                # MTP filesystem support for Kindle.
    - linux-headers
    - maim                  # Screen capture utility.
    - memcached
    - msmtp
    - mtpfs                 # MTP filesystem for Kindle.
    - net-tools
    - nmap
    - nodejs
    - noto-fonts            # Google Noto Font Family
    - noto-fonts-cjk        # Google Noto Font Family CJK
    - noto-fonts-emoji      # Google Noto Font Family Emoji
    - openssh
    - openssl
    - openvpn
    - pandoc
    - perl-image-exiftool   # EXIF reader/writer (example: edit PDF title)
    - pkg-config            # Retrieve information about installed binaries.
    - polkit
    - pulseaudio
    - pulseaudio-alsa
    - pygtk                 # Used by avahi-discover.
    - python
    - python2
    - python-pip
    - python2-pip
    - python-dbus           # Used by avahi-discover.
    - ranger                # Text-based file manager.
    - readline
    - recordmydesktop       # Screen record utility.
    - redis
    - rxvt-unicode          # Simple terminal when using X.
    - s3cmd                 # For syncing S3 buckets locally.
    - sane
    - screen
    - shellcheck            # Bash script linter.
    - slop                  # Allows selection with maim.
    - stylish-haskell       # Haskell Pretty Printer.
    - sxiv                  # Image Viewer
    - tar
    - tcpdump
    - the_silver_searcher   # (ag) Code search tool like Ack but faster.
    - tmux
    - traceroute
    - transset-df           # Transparency for Xcompmgr
    - tree
    - ttf-dejavu            # Fonts
    - valgrind              # C Development: test for memory usage errors.
    - vlc                   # Video player.
    - w3m
    - wireshark-gtk         # Network Packet Analyzer
    - xautolock
    - xclip
    - xcompmgr              # Composite Window Manager
    - xf86-input-synaptics
    - xmobar
    - xmonad
    - xmonad-contrib
    - xorg-server-xvfb
    - xorg-xdpyinfo         # Get info about X server, like screen resolution.
    - xorg-xinit
    - xorg-xprop            # Display window properties by clicking.
    - yaourt                # Provides easy installation for AUR packages.
    - zip                   # ZIP Utility
- include: yaourt.yml pkg=xcape
# Used to watch Netflix in chrome.
- include: yaourt.yml pkg=chromium-widevine
# Brother HL-L2360DW Printer Driver
- include: yaourt.yml pkg=brother-hll2360d
# Zoom Meeting Application
- include: yaourt.yml pkg=zoom
# Paragraph Reformatter
- include: yaourt.yml pkg=par
# Grip (GitHub Flavored Markdown Preview)
- include: yaourt.yml pkg=python-grip-git
# Userspace Software Suspend (used to retrieve resume_offset of swap file)
- include: yaourt.yml pkg=uswsusp-git
# acpilight (backward-compatible replacement for xbacklight)
- include: yaourt.yml pkg=acpilight
# Peek GIF Screen Recording Utility
- include: yaourt.yml pkg=peek
