---
- include: package-bundle.yml pkg=base-devel
- include: package-bundle.yml pkg=lxde
# Used for pandoc PDF conversions.
- include: package-bundle.yml pkg=texlive-most
- include: package-bundle.yml pkg=dnsutils
- name: Install Pacman Packages
  pacman: name={{ item }} state=present
  with_items:
    - abs
    - acpi
    - acpid
    - alsa-oss
    - alsa-utils
    - avahi
    - bc
    - bluez
    - bluez-utils
    - cabal-install
    - chromium              # Browser.
    - coreutils
    - crystal               # Crystal Programming Language
    - ctags
    - cups                  # Printer management.
    - curl
    - elixir                # Elixir Programming Language
    - encfs                 # File Encryption
    - erlang                # Full Erlang (for additional elixir functionality)
    - evince
    - exfat-utils           # exFAT filesystem support
    - expac
    - darktable             # Image Workflow and Editing
    - doxygen               # C Development: documentation generation.
    - gdb                   # C Development: debugger.
    - ghc                   # Haskell Compiler
    - ghostscript
    - glibc                 # C Development: GNU C Library.
    - gnupg
    - gnuplot               # GNU command line plotting utility
    - gsfonts
    - gsl                   # C Development: GNU Scientific Library.
    - gutenprint
    - guvcview              # Webcam configuration utility.
    - gvim
    - haskell-quickcheck    # Haskell testing library.
    - icedtea-web
    - imagemagick           # Image stuff and convert.
    - irssi
    - jq                    # Command-line JSON parser.
    - keepassx
    - keybase
    - libcups
    - libmtp                # MTP filesystem support for Kindle.
    - linux-headers
    - maim                  # Screen capture utility.
    - memcached
    - msmtp
    - mtpfs                 # MTP filesystem for Kindle.
    - net-tools
    - nmap
    - noto-fonts            # Google Noto Font Family
    - noto-fonts-cjk        # Google Noto Font Family CJK
    - noto-fonts-emoji      # Google Noto Font Family Emoji
    - openssh
    - openssl
    - openvpn
    - perl-image-exiftool   # EXIF reader/writer (example: edit PDF title)
    - pkg-config            # Retrieve information about installed binaries.
    - polkit
    - pulseaudio
    - pulseaudio-alsa
    - pygtk                 # Used by avahi-discover.
    - python
    - python2
    - python-pip
    - python2-pip
    - python-dbus           # Used by avahi-discover.
    - ranger                # Text-based file manager.
    - redis
    - rxvt-unicode          # Simple terminal when using X.
    - s3cmd                 # For syncing S3 buckets locally.
    - sane
    - screen
    - slop                  # Allows selection with maim.
    - stylish-haskell       # Haskell Pretty Printer.
    - sxiv                  # Image Viewer
    - tar
    - tcpdump
    - the_silver_searcher   # (ag) Code search tool like Ack but faster.
    - tmux
    - traceroute
    - tree
    - valgrind              # C Development: test for memory usage errors.
    - vlc                   # Video player.
    - w3m
    - wireshark-gtk         # Network Packet Analyzer
    - xautolock
    - xclip
    - xf86-input-synaptics
    - xf86-video-ati        # ATI/Radeon
    - xf86-video-fbdev
    - xf86-video-intel
    - xmobar
    - xmonad
    - xmonad-contrib
    - xorg-server-xvfb
    - xorg-xbacklight
    - xorg-xdpyinfo         # Get info about X server, like screen resolution.
    - xorg-xinit
    - xorg-xprop            # Display window properties by clicking.
    - yaourt                # Provides easy installation for AUR packages.
    - zip                   # ZIP Utility
- include: yaourt.yml pkg=xcape
# Used to watch Netflix in chrome.
- include: yaourt.yml pkg=chromium-widevine
- include: yaourt.yml pkg=spotify
# WiFi driver for MacBook Air.
- include: yaourt.yml pkg=broadcom-wl
# Video driver for MacBook Air built-in camera.
- include: yaourt.yml pkg=bcwc-pcie-firmware
- include: yaourt.yml pkg=bcwc-pcie-git
# Brother MFC-J4510DW Printer Driver
- include: yaourt.yml pkg=brother-mfc-j4510dw
# tmate.io (tmux remote pair programming)
- include: yaourt.yml pkg=tmate-git
# Zoom Meeting Application
- include: yaourt.yml pkg=zoom
# Paragraph Reformatter
- include: yaourt.yml pkg=par
