---
- include: package-bundle.yml pkg=base-devel
- include: package-bundle.yml pkg=lxde
# Used for pandoc PDF conversions.
- include: package-bundle.yml pkg=texlive-most
- include: package-bundle.yml pkg=dnsutils
- name: Install Pacman Packages
  pacman: name={{ item }} state=present
  with_items:
    - abs
    - acpi
    - acpid
    - alsa-oss
    - alsa-utils
    - avahi
    - bluez
    - bluez-utils
    - cairo                 # Fonts (Vector Graphics Library)
    - coreutils
    - cups                  # Printer management.
    - curl
    - encfs                 # File Encryption
    - eog                   # Image Viewer
    - evince                # PDF Viewer
    - exfat-utils           # exFAT filesystem support
    - expac
    - fontconfig            # Fonts
    - freetype2             # Fonts
    - ghostscript
    - gnupg
    - glibc                 # C Development: GNU C Library.
    - gnuplot               # GNU command line plotting utility
    - gsfonts
    - gthumb                # Simple Image Editor
    - gtk3
    - gutenprint
    - guvcview              # Webcam configuration utility.
    - gvim                  # Vim (with GTK/X support)
    - i3lock                # Screen Locker
    - imagemagick           # Image stuff and convert.
    - kdenlive              # Video Editing.
    - keepassx2             # Password Manager
    - libcups               # CUPS Printing Library
    - libmtp                # MTP filesystem support for Kindle.
    - linux-headers
    - maim                  # Screen capture utility.
    - msmtp
    - mtpfs                 # MTP filesystem for Kindle.
    - net-tools
    - nmap
    - noto-fonts            # Google Noto Font Family
    - noto-fonts-cjk        # Google Noto Font Family CJK
    - noto-fonts-emoji      # Google Noto Font Family Emoji
    - openssh
    - openssl
    - openvpn
    - pandoc
    - perl-image-exiftool   # EXIF reader/writer (example: edit PDF title)
    - pkg-config            # Retrieve information about installed binaries.
    - polkit
    - pulseaudio
    - pulseaudio-alsa
    - pygtk                 # Used by avahi-discover.
    - python
    - python2
    - python-pip
    - python2-pip
    - python-dbus           # Used by avahi-discover.
    - ranger                # Text-based file manager.
    - readline
    - recordmydesktop       # Screen record utility.
    - rxvt-unicode          # Simple terminal when using X.
    - s3cmd                 # For syncing S3 buckets locally.
    - sane
    - screen
    - shellcheck            # Bash script linter.
    - siege                 # Load testing and benchmarking tool.
    - slop                  # Allows selection with maim.
    - sxiv                  # Image Viewer
    - tar
    - tcpdump
    - tmux
    - traceroute
    - transset-df           # Transparency for Xcompmgr
    - tree
    - ttf-dejavu            # Fonts
    - vlc                   # Video player.
    - w3m
    - wireshark-gtk         # Network Packet Analyzer
    - xautolock             # Screen Locking
    - xclip
    - xcompmgr              # Composite Window Manager
    - xf86-input-synaptics
    - xmobar
    - xmonad
    - xmonad-contrib
    - xorg-server-xvfb
    - xorg-xdpyinfo         # Get info about X server, like screen resolution.
    - xorg-xinit
    - xorg-xprop            # Display window properties by clicking.
    - yaourt                # Provides easy installation for AUR packages.
    - zip                   # ZIP Utility
- name: Install Programming Packages
  pacman: name={{ item }} state=present
  with_items:
    - ctags
    - fzf                   # Command line fuzzy finder.
    - ghc                   # Haskell Compiler
    - haskell-quickcheck    # Haskell testing library.
    - hub                   # GitHub CLI for Git
    - memcached
    - nodejs
    - redis
    - stylish-haskell       # Haskell Pretty Printer.
    - the_silver_searcher   # (ag) Code search tool like Ack but faster.
- include: yaourt.yml pkg=xcape
# Google Chrome Browser
- include: yaourt.yml pkg=google-chrome
# Brother HL-L2360DW Printer Driver
- include: yaourt.yml pkg=brother-hll2360d
# Zoom Meeting Application
- include: yaourt.yml pkg=zoom
# Paragraph Reformatter
- include: yaourt.yml pkg=par
# Userspace Software Suspend (used to retrieve resume_offset of swap file)
- include: yaourt.yml pkg=uswsusp-git
# acpilight (backward-compatible replacement for xbacklight)
- include: yaourt.yml pkg=acpilight
# Peek GIF Screen Recording Utility
- include: yaourt.yml pkg=peek
# Graph Editor (flowcart, network, UML)
- include: yaourt.yml pkg=yed
# Keybase
- include: yaourt.yml pkg=keybase-bin
- pip:
    name: grip # GitHub Flavored Markdown Preview
