---
- hosts: localhost
  connection: local
  user: pan
  become: yes
  vars:
    user:
      name: pan
      groups: audio,docker,users,video,wireshark
    home: /home/pan
    ruby: 2.4.1
    node: 9.11.1
    network:
      iface: wlp58s0
  roles:
    - system
